main: yy.gourlitburo.yeyadaytime.Main
name: YeyaDaytime
version: 0.0.0
api-version: 1.15
author: Zack Guard
description: Sync world time with system time.
commands:
  yeyadaytime:
    aliases: [ydt]
    description: Manage YeyaDaytime.
    usage: "Usage: /ydt reload"
    permission: yeyadaytime.manage
permissions:
  yeyadaytime.manage:
    default: op
